### ISSUE TITLE
Update for v6

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-demo-ehr#480]
- [ ] Remove "user contract" auth means; not used in OpenID4VP-use cases any more
  - [ ] Remove IRMA
  - [ ] Remove session elevation
- [ ] Remove unsupported/unmaintained use cases
- [ ] ...
